name: Release
on: 
  push:
    tags:
    - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: TheDoctor0/zip-release@0.7.6
      with:
        type: 'zip'
        filename: 'mcskin-viewer.aseprite-extension'
        exclusions: '*.git* /*node_modules/* .editorconfig LICENSE README.md /*docs/*'

    - name: Create Release
      uses: ncipollo/release-action@v1.20.0
      with:
        artifacts: "mcskin-viewer.aseprite-extension"
