name: Release
on: 
  push:
    tags:
    - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: TheDoctor0/zip-release@0.7.6
      with:
        type: 'zip'
        filename: ${{format('mcskin-viewer{0}.aseprite-extension',  github.ref_name )}}
        exclusions: '*.git* /*node_modules/* .editorconfig LICENSE README.md /*docs/*'

    - name: Create Release
      uses: ncipollo/release-action@v1.20.0
      with:
        artifacts: ${{format('mcskin-viewer{0}.aseprite-extension',  github.ref_name )}}

    - name: Itch.io - Publish
      uses: KikimoraGames/itch-publish@v0.0.3
      with:
        butlerApiKey: ${{secrets.BUTLER_API_KEY}}
        gameData: ${{format('mcskin-viewer{0}.aseprite-extension',  github.ref_name )}}
        itchUsername: numa-smells
        itchGameId: aseprite-mc-skin-viewer
        buildChannel: mod
